"""Update message model and remove get-all-users endpoint

Revision ID: 10652a248349
Revises: 5dcecf81e130
Create Date: 2025-09-13 16:48:47.011818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10652a248349'
down_revision: Union[str, Sequence[str], None] = '5dcecf81e130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('query', sa.TEXT(), nullable=False))
    op.add_column('messages', sa.Column('response', sa.TEXT(), nullable=True))
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'response')
    op.drop_column('messages', 'query')
    # ### end Alembic commands ###
