"""Update message mode

Revision ID: 2b8af035289f
Revises: 10652a248349
Create Date: 2025-09-13 16:50:07.858149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8af035289f'
down_revision: Union[str, Sequence[str], None] = '10652a248349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_url', sa.TEXT(), nullable=True))
    op.add_column('messages', sa.Column('file_content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_content')
    op.drop_column('messages', 'file_url')
    # ### end Alembic commands ###
