"""uuid is defaulted to server

Revision ID: b33dd6f62b60
Revises: 1b0c8bfeaef3
Create Date: 2025-08-30 14:41:12.865765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33dd6f62b60'
down_revision: Union[str, Sequence[str], None] = '1b0c8bfeaef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
